---
title: "HW5-ZhanZ"
author: "Zhan, Zhuoyi"
date: "`r date()`"
output: github_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
library('MASS') ## for 'mcycle'
library('manipulate') ## for 'manipulate'

data(mcycle)

```
Randomly split the mcycle data into training (75%) and validation (25%) subsets.

```{r}
library(tidyverse)
df = as.data.frame(mcycle)
```

```{r}
smp_size <- floor(0.75 * nrow(mcycle))

## set the seed to make your partition reproducible
set.seed(123)
train_ind <- sample(seq_len(nrow(mcycle)), size = smp_size)

train <- mcycle[train_ind, ]
test <- mcycle[-train_ind, ]
```

Using the mcycle data, consider predicting the mean acceleration as a function of time. Use the Nadaraya-Watson method with the k-NN kernel function to create a series of prediction models by varying the tuning parameter over a sequence of values. (hint: the script already implements this)

```{r}
kernel_k_nearest_neighbors <- function(x, x0, k=1) {
  ## compute distance betwen each x and x0
  z <- t(t(x) - x0)
  d <- sqrt(rowSums(z*z))

  ## initialize kernel weights to zero
  w <- rep(0, length(d))
  
  ## set weight to 1 for k nearest neighbors
  w[order(d)[1:k]] <- 1
  
  return(w)
}

nadaraya_watson <- function(y, x, x0, kern, ...) {
  k <- t(apply(x0, 1, function(x0_) {
    k_ <- kern(x, x0_, ...)
    k_/sum(k_)
  }))
  yhat <- drop(k %*% y)
  attr(yhat, 'k') <- k
  return(yhat)
}

```

